apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: ui-admin-preview
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ui-admin-design
  filterTags:
    pattern: '^[a-f0-9]+-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
