compressionLevel: mixed

defaultSemverRangePrefix: ''

preferReuse: true

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@svgr/core@*':
    dependencies:
      'prettier': '*'
      'svgo': '*'
      '@types/babel__core': '*'
      '@svgr/plugin-jsx': '*'
      '@svgr/plugin-svgo': '*'
      '@svgr/plugin-prettier': '*'
  '@svgr/babel-plugin-transform-svg-component@*':
    dependencies:
      '@babel/template': '*'
      '@types/babel__template': '*'
  '@types/react@*':
    dependencies:
      scheduler: '0.20.2'
  '@emotion/utils@*':
    dependencies:
      '@emotion/sheet': '*'
  '@storybook/react@*':
    dependencies:
      '@storybook/test': '*'
  '@storybook/node-logger@*':
    dependencies:
      'storybook': '*'
  '@storybook/types@*':
    dependencies:
      '@types/react': '*'
  '@storybook/builder-webpack5@*':
    dependencies:
      'file-system-cache': '2.3.0'
  '@storybook/addon-webpack5-compiler-swc@*':
    dependencies:
      'semver': '*'
  '@storybook/preset-react-webpack@*':
    dependencies:
      'file-system-cache': '2.3.0'
  react-datepicker@*:
    dependencies:
      '@types/react-onclickoutside': '*'
  swiper@*:
    dependencies:
      '@types/react': '*'
  graphql-request@*:
    dependencies:
      type-fest: '*'
  framer-motion@*:
    dependencies:
      '@emotion/is-prop-valid': '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-remote.mjs
