compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

globalFolder: ../.yarn/berry

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  atls:
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@emotion/utils@*":
    dependencies:
      "@emotion/sheet": "*"
  "@storybook/addon-webpack5-compiler-swc@*":
    dependencies:
      semver: "*"
  "@storybook/builder-webpack5@*":
    dependencies:
      file-system-cache: 2.3.0
  "@storybook/node-logger@*":
    dependencies:
      storybook: "*"
  "@storybook/preset-react-webpack@*":
    dependencies:
      file-system-cache: 2.3.0
  "@storybook/react@*":
    dependencies:
      "@storybook/test": "*"
  "@storybook/types@*":
    dependencies:
      "@types/react": "*"
  "@svgr/babel-plugin-transform-svg-component@*":
    dependencies:
      "@babel/template": "*"
      "@types/babel__template": "*"
  "@svgr/core@*":
    dependencies:
      "@svgr/plugin-jsx": "*"
      "@svgr/plugin-prettier": "*"
      "@svgr/plugin-svgo": "*"
      "@types/babel__core": "*"
      prettier: "*"
      svgo: "*"
  "@types/react@*":
    dependencies:
      scheduler: 0.20.2
  framer-motion@*:
    dependencies:
      "@emotion/is-prop-valid": "*"
  graphql-request@*:
    dependencies:
      type-fest: "*"
  react-datepicker@*:
    dependencies:
      "@types/react-onclickoutside": "*"
  swiper@*:
    dependencies:
      "@types/react": "*"

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
