packageExtensions:
  '@storybook/components@*':
    dependencies:
      '@emotion/styled-base': '*'
      '@storybook/api': '*'
  '@storybook/core-server@*':
    dependencies:
      '@storybook/manager-webpack5': '*'
  '@storybook/theming@*':
    dependencies:
      '@emotion/utils': '*'
      '@emotion/serialize': '*'
  '@storybook/react@*':
    dependencies:
      '@storybook/builder-webpack5': '*'
  '@storybook/addons@*':
    dependencies:
      '@types/webpack-env': '*'
  '@testing-library/react@*':
    dependencies:
      pretty-format: '*'
      react-dom: '*'
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
  next@*:
    dependencies:
      '@types/react-dom': '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220409.hash-0390372.cjs
