packageExtensions:
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': 11.4.0
  '@storybook/addons@*':
    dependencies:
      '@types/webpack-env': '*'
  '@storybook/components@*':
    dependencies:
      '@emotion/styled-base': '*'
      '@storybook/api': '*'
  '@storybook/react@*':
    dependencies:
      '@storybook/builder-webpack5': '*'
  '@storybook/theming@*':
    dependencies:
      '@emotion/serialize': '*'
      '@emotion/utils': '*'
  '@testing-library/react@*':
    dependencies:
      pretty-format: '*'
      react-dom: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  next@*:
    dependencies:
      '@types/react-dom': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - .yarn/plugins/plugin-build-storybook-addons.cjs
  - .yarn/plugins/@atls/plugin-essentials.cjs

yarnPath: .yarn/releases/yarn-3.0.2.cjs
