packageExtensions:
  '@storybook/node-logger@*':
    dependencies:
      'storybook': '*'
  '@storybook/core@*':
    dependencies:
      '@types/react': '*'
  '@testing-library/react@*':
    dependencies:
      pretty-format: '*'
      react-dom: '*'
  swiper@*:
    dependencies:
      '@types/react': '*'
  next@*:
    dependencies:
      '@types/react-dom': '*'
      'util': '*'

yarnPath: .yarn/releases/yarn-remote.cjs
enableGlobalCache: false
