compressionLevel: mixed

defaultSemverRangePrefix: ''

preferReuse: true

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@types/react@*':
    dependencies:
      scheduler: '0.20.2'
  '@emotion/utils@*':
    dependencies:
      '@emotion/sheet': '*'
  '@storybook/node-logger@*':
    dependencies:
      'storybook': '*'
  '@storybook/types@*':
    dependencies:
      '@types/react': '*'
  '@storybook/builder-webpack5@*':
    dependencies:
      'file-system-cache': '2.3.0'
  '@storybook/preset-react-webpack@*':
    dependencies:
      'file-system-cache': '2.3.0'
  '@testing-library/react@*':
    dependencies:
      pretty-format: '*'
      react-dom: '*'
  swiper@*:
    dependencies:
      '@types/react': '*'
  graphql-request@*:
    dependencies:
      type-fest: '*'
  framer-motion@*:
    dependencies:
      '@emotion/is-prop-valid': '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-remote.cjs
