packageExtensions:
  '@emotion/utils@*':
    dependencies:
      '@emotion/sheet': '*'
  '@storybook/node-logger@*':
    dependencies:
      'storybook': '*'
  '@storybook/types@*':
    dependencies:
      '@types/react': '*'
  '@storybook/builder-webpack5@*':
    dependencies:
      'file-system-cache': '2.3.0'
  '@storybook/preset-react-webpack@*':
    dependencies:
      'file-system-cache': '2.3.0'
  '@storybook/core@*':
    dependencies:
      '@types/react': '*'
  '@testing-library/react@*':
    dependencies:
      pretty-format: '*'
      react-dom: '*'
  swiper@*:
    dependencies:
      '@types/react': '*'
  graphql-request@*:
    dependencies:
      type-fest: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
enableGlobalCache: false
