compressionLevel: mixed

defaultSemverRangePrefix: ''

preferReuse: true

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@storybook/node-logger@*':
    dependencies:
      storybook: '*'
  '@testing-library/react@*':
    dependencies:
      pretty-format: '*'
      react-dom: '*'
  next@*:
    dependencies:
      '@types/react-dom': '*'
      'util': '*'

yarnPath: .yarn/releases/yarn-remote.cjs
