packageExtensions:
  "@emotion/styled@*":
    dependencies:
      "@emotion/react": "*"
  "@storybook/addons@*":
    dependencies:
      "@types/webpack-env": "*"
  "@storybook/components@*":
    dependencies:
      "@emotion/styled-base": "*"
      "@storybook/api": "*"
  "@storybook/core-server@*":
    dependencies:
      "@storybook/manager-webpack5": "*"
  "@storybook/react@*":
    dependencies:
      "@storybook/builder-webpack5": "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  "@testing-library/react@*":
    dependencies:
      pretty-format: "*"
      react-dom: "*"
  next@*:
    dependencies:
      "@types/react-dom": "*"

yarnPath: .yarn/releases/yarn-0.0.1-git.20220426.hash-a30b37d.cjs
