packageExtensions:
  '@storybook/node-logger@*':
    dependencies:
      storybook: '*'
  '@testing-library/react@*':
    dependencies:
      pretty-format: '*'
      react-dom: '*'
  next@*:
    dependencies:
      '@types/react-dom': '*'
      'util': '*'

yarnPath: .yarn/releases/yarn-remote.cjs
enableGlobalCache: false
