packageExtensions:
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
  '@storybook/addon-docs@*':
    dependencies:
      '@babel/core': '*'
  '@storybook/addons@*':
    dependencies:
      '@types/webpack-env': '*'
  '@storybook/components@*':
    dependencies:
      '@emotion/styled-base': '*'
      '@storybook/api': '*'
  '@storybook/core-server@*':
    dependencies:
      '@storybook/manager-webpack5': '*'
  '@storybook/react@*':
    dependencies:
      '@storybook/builder-webpack5': '*'
  '@storybook/router@*':
    dependencies:
      util: '*'
  '@storybook/theming@*':
    dependencies:
      '@emotion/serialize': '*'
      '@emotion/utils': '*'
  '@storybook/ui@*':
    dependencies:
      util: '*'
  '@testing-library/react@*':
    dependencies:
      pretty-format: '*'
      react-dom: '*'
  framer-motion@*:
    dependencies:
      csstype: '*'
  glob-promise@*:
    dependencies:
      glob: '*'
  next@*:
    dependencies:
      '@types/react-dom': '*'

yarnPath: .yarn/releases/yarn-remote.cjs
enableGlobalCache: false
