version: '3.8'

services:
  yarn:
    image: node:16.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  parts-design:
    image: node:16.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @atls-ui-parts/design dev
    networks:
      - default
    ports:
      - 3000:3000

  proto-design:
    image: node:16.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @atls-ui-proto/design dev
    networks:
      - default
    ports:
      - 3000:3000
