export const storybookSwcCompilerAddon = '@storybook/addon-webpack5-compiler-swc'
export const storybookLinksAddon = '@storybook/addon-links'
export const storybookDocsAddon = '@storybook/addon-docs'
export const chromaticStorybookAddon = '@chromatic-com/storybook'
export const storybookStylingWebpackAddon = '@storybook/addon-styling-webpack'
