apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ui
  namespace: istio-system
spec:
  secretName: ui-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'ui.atls.tech'
  dnsNames:
    - 'ui.atls.tech'
