export type ColorsTokens = Record<keyof typeof colorsContract, string>

export const colorsContract = {
  blue: null,
  blueProtective: null,
  white: null,
  red: null,
  green: null,
  gray: null,
  black: null,
  blackThreeQuarters: null,
  lightPurple: null,

  'button.blue.default.font': null,
  'button.blue.default.background': null,
  'button.blue.default.border': null,
  'button.blue.hover.font': null,
  'button.blue.hover.background': null,
  'button.blue.hover.border': null,
  'button.blue.pressed.font': null,
  'button.blue.pressed.background': null,
  'button.blue.pressed.border': null,
  'button.blue.disabled.font': null,
  'button.blue.disabled.background': null,
  'button.blue.disabled.border': null,

  'button.lightBlue.default.font': null,
  'button.lightBlue.default.background': null,
  'button.lightBlue.default.border': null,
  'button.lightBlue.hover.font': null,
  'button.lightBlue.hover.background': null,
  'button.lightBlue.hover.border': null,
  'button.lightBlue.pressed.font': null,
  'button.lightBlue.pressed.background': null,
  'button.lightBlue.pressed.border': null,
  'button.lightBlue.disabled.font': null,
  'button.lightBlue.disabled.background': null,
  'button.lightBlue.disabled.border': null,

  'text.white': null,
  'text.black': null,
  'text.almostBlack': null,
  'text.masala': null,
  'text.gray': null,
  'text.regularGray': null,
  'text.normalGray': null,
  'text.warmGray': null,
  'text.darkGray': null,
  'text.deepGray': null,
  'text.lightGray': null,
  'text.shadylady': null,
  'text.blue': null,
  'text.lightBlue': null,
  'text.red': null,
  'text.softBlue': null,
  'text.green': null,

  'icons.placeholder': null,
}
