export type ShadowsTokens = Record<keyof typeof shadowsContract, string>

export const shadowsContract = {
  gunsmoke: null,
  gray: null,
  grey: null,
  suvagray: null,
  oslogray: null,
  black: null,
  codgray: null,
  woodsmoke: null,
  asphalt: null,
  marshland: null,
  bunker: null,
  nero: null,
  diesel: null,
  gordonsgreen: null,
  jaguar: null,
  midnightmoss: null,
  cinder: null,
  darkgray: null,
  portage: null,
  blackforest: null,
  greenwaterloo: null,
  crowshead: null,
  bluecharcoal: null,
  vulcan: null,
  nightrider: null,
  transparentGray: null,
  lightTransparentGray: null,
  mediumTransparentGray: null,
  normalTransparentGray: null,
  regularTransparentGray: null,
  regularGray: null,
}
