apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ui-proto
  namespace: istio-system
spec:
  secretName: ui-proto-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'ui-proto.ui.atls.tech'
  dnsNames:
    - 'ui-proto.ui.atls.tech'
