export type FontSizesTokens = Record<keyof typeof fontSizesContract, string>

export const fontSizesContract = {
  inherit: null,
  max: null,
  semiTiny: null,
  semiSmall: null,
  small: null,
  tiny: null,
  semiMicro: null,
  micro: null,
  semiBold: null,
  middling: null,
  medium: null,
  semiRegular: null,
  regular: null,
  semiLarge: null,
  large: null,
  semiModerate: null,
  moderate: null,
  mild: null,
  semiIncreased: null,
  increased: null,
  semiBig: null,
  big: null,
  semiExtra: null,
  extra: null,
  semiMassive: null,
  massive: null,
  godzilla: null,
  semiHuge: null,
  huge: null,
  semiGiant: null,
  semiGigantic: null,
}
