name: Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - edited
    paths-ignore:
      - '.github/**'

jobs:
  check:
    name: Checks
    uses: atls/shared/.github/workflows/checks.yaml@master
    permissions: write-all
