name: Checks

on:
  pull_request:
    paths:
      - '*'
      - '*/*'
      - '*/*/*'
      - '*/*/*/*'
      - '*/*/*/*/*'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.1'

      - name: Install
        run: yarn install

      - name: TypeCheck
        run: yarn mctl check:typecheck
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Lint
        run: yarn mctl check:lint
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
