name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  release:
    uses: atls/shared/.github/workflows/pack-image.yaml@master
    permissions: write-all
    with:
      registryURL: 'cr.yandex'
      registryUser: 'json_key'
    secrets:
      registryKey: ${{ secrets.YCR_KEYFILE }}
      project: ${{ secrets.YCR_PROJECT_ID }}
