name: Publish Packages
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'master'
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'master'
      - name: Install
        run: yarn install
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'master'
      - name: Build
        run: yarn build
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'master'
      - name: Configure GPG Key
        run: |
          mkdir -p ~/.gnupg/
          printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
          gpg --import ~/.gnupg/private.key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'master'
      - name: Configure Git User
        run: |
          git config --local user.email $GIT_EMAIL
          git config --local user.name $GIT_USER
          git config --local user.signingkey $GPG_KEY_ID
          git config --local commit.gpgsign true
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID}}
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'master'
      - name: Configure .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'master'
      - name: Release and Publish
        run: |
          yarn lerna version --yes
          yarn lerna publish from-package --no-verify-access --yes --registry="https://npm.pkg.github.com/:_authToken=$NPM_TOKEN"
          yarn lerna publish from-package --no-verify-access --yes --registry="https://registry.npmjs.org/:_authToken=$NPM_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'master'
