name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    uses: atls/shared/.github/workflows/publish.yaml@master
    permissions: write-all
    secrets:
      npmAuthToken: ${{ secrets.NPM_TOKEN }}
