name: Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths-ignore:
      - '.github/**'

jobs:
  release:
    if: github.event.pull_request.merged == true
    uses: atls/shared/.github/workflows/pack-image.yaml@master
    permissions: write-all
    with:
      registryURL: 'cr.yandex'
      registryUser: 'json_key'
      project: ${{ secrets.YCR_PROJECT_ID }}
    secrets:
      registryKey: ${{ secrets.YCR_KEYFILE }}
