name: Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths-ignore:
      - '.github/**'

jobs:
  release:
    uses: atls/shared/.github/workflows/pack-image.yaml@master
    permissions: write-all
    with:
      registryURL: 'ghcr.io'
      registryUser: ${{ github.repository_owner }}
      project: ${{ github.repository_owner }}
    secrets:
      registryKey: ${{ secrets.GITHUB_TOKEN }}
