name: Version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  run:
    name: Version
    uses: atls/tools/.github/workflows/reusable-version.yaml@master
    permissions: write-all
