export const storybookBuildCommand = 'build'
export const storybookDevCommand = 'dev'
export const yarnBinary = 'yarn'
export const storybookBinary = 'storybook'
export const configDirOption = '--config-dir'
export const outputDirOption = '-o'
export const portOption = '-p'
export const unknownExitCode = 'unknown'
